[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "page-tracker"
version = "1.0.0"
dependencies = [
  "Flask",
  "redis",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-timeout",
]
